const api = require('./api');

api.functions = {
  'FMOD_Memory_Initialize': ['int', ['void*', 'int', 'void*', 'void*', 'void*', 'Uint']],
  'FMOD_Memory_GetStats': ['int', ['int*', 'int*', 'int']],
  'FMOD_Debug_Initialize': ['int', ['Uint', 'int', 'void*', 'string']],
  'FMOD_File_SetDiskBusy': ['int', ['int']],
  'FMOD_File_GetDiskBusy': ['int', ['int*']],
  'FMOD_Thread_SetAttributes': ['int', ['int', 'longlong', 'int', 'Uint']],
  'FMOD_System_Create': ['int', ['void**', 'Uint']],
  'FMOD_System_Release': ['int', ['void*']],
  'FMOD_System_SetOutput': ['int', ['void*', 'int']],
  'FMOD_System_GetOutput': ['int', ['void*', 'int*']],
  'FMOD_System_GetNumDrivers': ['int', ['void*', 'int*']],
  'FMOD_System_GetDriverInfo': ['int', ['void*', 'int', 'string', 'int', 'void*', 'int*', 'int*', 'int*']],
  'FMOD_System_SetDriver': ['int', ['void*', 'int']],
  'FMOD_System_GetDriver': ['int', ['void*', 'int*']],
  'FMOD_System_SetSoftwareChannels': ['int', ['void*', 'int']],
  'FMOD_System_GetSoftwareChannels': ['int', ['void*', 'int*']],
  'FMOD_System_SetSoftwareFormat': ['int', ['void*', 'int', 'int', 'int']],
  'FMOD_System_GetSoftwareFormat': ['int', ['void*', 'int*', 'int*', 'int*']],
  'FMOD_System_SetDSPBufferSize': ['int', ['void*', 'Uint', 'int']],
  'FMOD_System_GetDSPBufferSize': ['int', ['void*', 'Uint*', 'int*']],
  'FMOD_System_SetFileSystem': ['int', ['void*', 'void*', 'void*', 'void*', 'void*', 'void*', 'void*', 'int']],
  'FMOD_System_AttachFileSystem': ['int', ['void*', 'void*', 'void*', 'void*', 'void*']],
  'FMOD_System_SetAdvancedSettings': ['int', ['void*', 'void*']],
  'FMOD_System_GetAdvancedSettings': ['int', ['void*', 'void*']],
  'FMOD_System_SetCallback': ['int', ['void*', 'void*', 'int']],
  'FMOD_System_SetPluginPath': ['int', ['void*', 'string']],
  'FMOD_System_LoadPlugin': ['int', ['void*', 'string', 'Uint*', 'Uint']],
  'FMOD_System_UnloadPlugin': ['int', ['void*', 'Uint']],
  'FMOD_System_GetNumNestedPlugins': ['int', ['void*', 'Uint', 'int*']],
  'FMOD_System_GetNestedPlugin': ['int', ['void*', 'Uint', 'int', 'Uint*']],
  'FMOD_System_GetNumPlugins': ['int', ['void*', 'int', 'int*']],
  'FMOD_System_GetPluginHandle': ['int', ['void*', 'int', 'int', 'Uint*']],
  'FMOD_System_GetPluginInfo': ['int', ['void*', 'Uint', 'int*', 'string', 'int', 'Uint*']],
  'FMOD_System_SetOutputByPlugin': ['int', ['void*', 'Uint']],
  'FMOD_System_GetOutputByPlugin': ['int', ['void*', 'Uint*']],
  'FMOD_System_CreateDSPByPlugin': ['int', ['void*', 'Uint', 'void**']],
  'FMOD_System_GetDSPInfoByPlugin': ['int', ['void*', 'Uint', 'void**']],
  'FMOD_System_RegisterCodec': ['int', ['void*', 'void*', 'Uint*', 'Uint']],
  'FMOD_System_RegisterDSP': ['int', ['void*', 'void*', 'Uint*']],
  'FMOD_System_RegisterOutput': ['int', ['void*', 'void*', 'Uint*']],
  'FMOD_System_Init': ['int', ['void*', 'int', 'Uint', 'void*']],
  'FMOD_System_Close': ['int', ['void*']],
  'FMOD_System_Update': ['int', ['void*']],
  'FMOD_System_SetSpeakerPosition': ['int', ['void*', 'int', 'float', 'float', 'int']],
  'FMOD_System_GetSpeakerPosition': ['int', ['void*', 'int', 'float*', 'float*', 'int*']],
  'FMOD_System_SetStreamBufferSize': ['int', ['void*', 'Uint', 'Uint']],
  'FMOD_System_GetStreamBufferSize': ['int', ['void*', 'Uint*', 'Uint*']],
  'FMOD_System_Set3DSettings': ['int', ['void*', 'float', 'float', 'float']],
  'FMOD_System_Get3DSettings': ['int', ['void*', 'float*', 'float*', 'float*']],
  'FMOD_System_Set3DNumListeners': ['int', ['void*', 'int']],
  'FMOD_System_Get3DNumListeners': ['int', ['void*', 'int*']],
  'FMOD_System_Set3DListenerAttributes': ['int', ['void*', 'int', 'void*', 'void*', 'void*', 'void*']],
  'FMOD_System_Get3DListenerAttributes': ['int', ['void*', 'int', 'void*', 'void*', 'void*', 'void*']],
  'FMOD_System_Set3DRolloffCallback': ['int', ['void*', 'void*']],
  'FMOD_System_MixerSuspend': ['int', ['void*']],
  'FMOD_System_MixerResume': ['int', ['void*']],
  'FMOD_System_GetDefaultMixMatrix': ['int', ['void*', 'int', 'int', 'float*', 'int']],
  'FMOD_System_GetSpeakerModeChannels': ['int', ['void*', 'int', 'int*']],
  'FMOD_System_GetVersion': ['int', ['void*', 'Uint*']],
  'FMOD_System_GetOutputHandle': ['int', ['void*', 'void**']],
  'FMOD_System_GetChannelsPlaying': ['int', ['void*', 'int*', 'int*']],
  'FMOD_System_GetCPUUsage': ['int', ['void*', 'void*']],
  'FMOD_System_GetFileUsage': ['int', ['void*', 'longlong*', 'longlong*', 'longlong*']],
  'FMOD_System_CreateSound': ['int', ['void*', 'string', 'Uint', 'void*', 'void**']],
  'FMOD_System_CreateStream': ['int', ['void*', 'string', 'Uint', 'void*', 'void**']],
  'FMOD_System_CreateDSP': ['int', ['void*', 'void*', 'void**']],
  'FMOD_System_CreateDSPByType': ['int', ['void*', 'int', 'void**']],
  'FMOD_System_CreateChannelGroup': ['int', ['void*', 'string', 'void**']],
  'FMOD_System_CreateSoundGroup': ['int', ['void*', 'string', 'void**']],
  'FMOD_System_CreateReverb3D': ['int', ['void*', 'void**']],
  'FMOD_System_PlaySound': ['int', ['void*', 'void*', 'void*', 'int', 'void**']],
  'FMOD_System_PlayDSP': ['int', ['void*', 'void*', 'void*', 'int', 'void**']],
  'FMOD_System_GetChannel': ['int', ['void*', 'int', 'void**']],
  'FMOD_System_GetDSPInfoByType': ['int', ['void*', 'int', 'void**']],
  'FMOD_System_GetMasterChannelGroup': ['int', ['void*', 'void**']],
  'FMOD_System_GetMasterSoundGroup': ['int', ['void*', 'void**']],
  'FMOD_System_AttachChannelGroupToPort': ['int', ['void*', 'int', 'Ulonglong', 'void*', 'int']],
  'FMOD_System_DetachChannelGroupFromPort': ['int', ['void*', 'void*']],
  'FMOD_System_SetReverbProperties': ['int', ['void*', 'int', 'void*']],
  'FMOD_System_GetReverbProperties': ['int', ['void*', 'int', 'void*']],
  'FMOD_System_LockDSP': ['int', ['void*']],
  'FMOD_System_UnlockDSP': ['int', ['void*']],
  'FMOD_System_GetRecordNumDrivers': ['int', ['void*', 'int*', 'int*']],
  'FMOD_System_GetRecordDriverInfo': ['int', ['void*', 'int', 'string', 'int', 'void*', 'int*', 'int*', 'int*', 'Uint*']],
  'FMOD_System_GetRecordPosition': ['int', ['void*', 'int', 'Uint*']],
  'FMOD_System_RecordStart': ['int', ['void*', 'int', 'void*', 'int']],
  'FMOD_System_RecordStop': ['int', ['void*', 'int']],
  'FMOD_System_IsRecording': ['int', ['void*', 'int', 'int*']],
  'FMOD_System_CreateGeometry': ['int', ['void*', 'int', 'int', 'void**']],
  'FMOD_System_SetGeometrySettings': ['int', ['void*', 'float']],
  'FMOD_System_GetGeometrySettings': ['int', ['void*', 'float*']],
  'FMOD_System_LoadGeometry': ['int', ['void*', 'void*', 'int', 'void**']],
  'FMOD_System_GetGeometryOcclusion': ['int', ['void*', 'void*', 'void*', 'float*', 'float*']],
  'FMOD_System_SetNetworkProxy': ['int', ['void*', 'string']],
  'FMOD_System_GetNetworkProxy': ['int', ['void*', 'string', 'int']],
  'FMOD_System_SetNetworkTimeout': ['int', ['void*', 'int']],
  'FMOD_System_GetNetworkTimeout': ['int', ['void*', 'int*']],
  'FMOD_System_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_System_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_Sound_Release': ['int', ['void*']],
  'FMOD_Sound_GetSystemObject': ['int', ['void*', 'void**']],
  'FMOD_Sound_Lock': ['int', ['void*', 'Uint', 'Uint', 'void**', 'void**', 'Uint*', 'Uint*']],
  'FMOD_Sound_Unlock': ['int', ['void*', 'void*', 'void*', 'Uint', 'Uint']],
  'FMOD_Sound_SetDefaults': ['int', ['void*', 'float', 'int']],
  'FMOD_Sound_GetDefaults': ['int', ['void*', 'float*', 'int*']],
  'FMOD_Sound_Set3DMinMaxDistance': ['int', ['void*', 'float', 'float']],
  'FMOD_Sound_Get3DMinMaxDistance': ['int', ['void*', 'float*', 'float*']],
  'FMOD_Sound_Set3DConeSettings': ['int', ['void*', 'float', 'float', 'float']],
  'FMOD_Sound_Get3DConeSettings': ['int', ['void*', 'float*', 'float*', 'float*']],
  'FMOD_Sound_Set3DCustomRolloff': ['int', ['void*', 'void*', 'int']],
  'FMOD_Sound_Get3DCustomRolloff': ['int', ['void*', 'void**', 'int*']],
  'FMOD_Sound_GetSubSound': ['int', ['void*', 'int', 'void**']],
  'FMOD_Sound_GetSubSoundParent': ['int', ['void*', 'void**']],
  'FMOD_Sound_GetName': ['int', ['void*', 'string', 'int']],
  'FMOD_Sound_GetLength': ['int', ['void*', 'Uint*', 'Uint']],
  'FMOD_Sound_GetFormat': ['int', ['void*', 'int*', 'int*', 'int*', 'int*']],
  'FMOD_Sound_GetNumSubSounds': ['int', ['void*', 'int*']],
  'FMOD_Sound_GetNumTags': ['int', ['void*', 'int*', 'int*']],
  'FMOD_Sound_GetTag': ['int', ['void*', 'string', 'int', 'void*']],
  'FMOD_Sound_GetOpenState': ['int', ['void*', 'int*', 'Uint*', 'int*', 'int*']],
  'FMOD_Sound_ReadData': ['int', ['void*', 'void*', 'Uint', 'Uint*']],
  'FMOD_Sound_SeekData': ['int', ['void*', 'Uint']],
  'FMOD_Sound_SetSoundGroup': ['int', ['void*', 'void*']],
  'FMOD_Sound_GetSoundGroup': ['int', ['void*', 'void**']],
  'FMOD_Sound_GetNumSyncPoints': ['int', ['void*', 'int*']],
  'FMOD_Sound_GetSyncPoint': ['int', ['void*', 'int', 'void**']],
  'FMOD_Sound_GetSyncPointInfo': ['int', ['void*', 'void*', 'string', 'int', 'Uint*', 'Uint']],
  'FMOD_Sound_AddSyncPoint': ['int', ['void*', 'Uint', 'Uint', 'string', 'void**']],
  'FMOD_Sound_DeleteSyncPoint': ['int', ['void*', 'void*']],
  'FMOD_Sound_SetMode': ['int', ['void*', 'Uint']],
  'FMOD_Sound_GetMode': ['int', ['void*', 'Uint*']],
  'FMOD_Sound_SetLoopCount': ['int', ['void*', 'int']],
  'FMOD_Sound_GetLoopCount': ['int', ['void*', 'int*']],
  'FMOD_Sound_SetLoopPoints': ['int', ['void*', 'Uint', 'Uint', 'Uint', 'Uint']],
  'FMOD_Sound_GetLoopPoints': ['int', ['void*', 'Uint*', 'Uint', 'Uint*', 'Uint']],
  'FMOD_Sound_GetMusicNumChannels': ['int', ['void*', 'int*']],
  'FMOD_Sound_SetMusicChannelVolume': ['int', ['void*', 'int', 'float']],
  'FMOD_Sound_GetMusicChannelVolume': ['int', ['void*', 'int', 'float*']],
  'FMOD_Sound_SetMusicSpeed': ['int', ['void*', 'float']],
  'FMOD_Sound_GetMusicSpeed': ['int', ['void*', 'float*']],
  'FMOD_Sound_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_Sound_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_Channel_GetSystemObject': ['int', ['void*', 'void**']],
  'FMOD_Channel_Stop': ['int', ['void*']],
  'FMOD_Channel_SetPaused': ['int', ['void*', 'int']],
  'FMOD_Channel_GetPaused': ['int', ['void*', 'int*']],
  'FMOD_Channel_SetVolume': ['int', ['void*', 'float']],
  'FMOD_Channel_GetVolume': ['int', ['void*', 'float*']],
  'FMOD_Channel_SetVolumeRamp': ['int', ['void*', 'int']],
  'FMOD_Channel_GetVolumeRamp': ['int', ['void*', 'int*']],
  'FMOD_Channel_GetAudibility': ['int', ['void*', 'float*']],
  'FMOD_Channel_SetPitch': ['int', ['void*', 'float']],
  'FMOD_Channel_GetPitch': ['int', ['void*', 'float*']],
  'FMOD_Channel_SetMute': ['int', ['void*', 'int']],
  'FMOD_Channel_GetMute': ['int', ['void*', 'int*']],
  'FMOD_Channel_SetReverbProperties': ['int', ['void*', 'int', 'float']],
  'FMOD_Channel_GetReverbProperties': ['int', ['void*', 'int', 'float*']],
  'FMOD_Channel_SetLowPassGain': ['int', ['void*', 'float']],
  'FMOD_Channel_GetLowPassGain': ['int', ['void*', 'float*']],
  'FMOD_Channel_SetMode': ['int', ['void*', 'Uint']],
  'FMOD_Channel_GetMode': ['int', ['void*', 'Uint*']],
  'FMOD_Channel_SetCallback': ['int', ['void*', 'void*']],
  'FMOD_Channel_IsPlaying': ['int', ['void*', 'int*']],
  'FMOD_Channel_SetPan': ['int', ['void*', 'float']],
  'FMOD_Channel_SetMixLevelsOutput': ['int', ['void*', 'float', 'float', 'float', 'float', 'float', 'float', 'float', 'float']],
  'FMOD_Channel_SetMixLevelsInput': ['int', ['void*', 'float*', 'int']],
  'FMOD_Channel_SetMixMatrix': ['int', ['void*', 'float*', 'int', 'int', 'int']],
  'FMOD_Channel_GetMixMatrix': ['int', ['void*', 'float*', 'int*', 'int*', 'int']],
  'FMOD_Channel_GetDSPClock': ['int', ['void*', 'Ulonglong*', 'Ulonglong*']],
  'FMOD_Channel_SetDelay': ['int', ['void*', 'Ulonglong', 'Ulonglong', 'int']],
  'FMOD_Channel_GetDelay': ['int', ['void*', 'Ulonglong*', 'Ulonglong*', 'int*']],
  'FMOD_Channel_AddFadePoint': ['int', ['void*', 'Ulonglong', 'float']],
  'FMOD_Channel_SetFadePointRamp': ['int', ['void*', 'Ulonglong', 'float']],
  'FMOD_Channel_RemoveFadePoints': ['int', ['void*', 'Ulonglong', 'Ulonglong']],
  'FMOD_Channel_GetFadePoints': ['int', ['void*', 'Uint*', 'Ulonglong*', 'float*']],
  'FMOD_Channel_GetDSP': ['int', ['void*', 'int', 'void**']],
  'FMOD_Channel_AddDSP': ['int', ['void*', 'int', 'void*']],
  'FMOD_Channel_RemoveDSP': ['int', ['void*', 'void*']],
  'FMOD_Channel_GetNumDSPs': ['int', ['void*', 'int*']],
  'FMOD_Channel_SetDSPIndex': ['int', ['void*', 'void*', 'int']],
  'FMOD_Channel_GetDSPIndex': ['int', ['void*', 'void*', 'int*']],
  'FMOD_Channel_Set3DAttributes': ['int', ['void*', 'void*', 'void*']],
  'FMOD_Channel_Get3DAttributes': ['int', ['void*', 'void*', 'void*']],
  'FMOD_Channel_Set3DMinMaxDistance': ['int', ['void*', 'float', 'float']],
  'FMOD_Channel_Get3DMinMaxDistance': ['int', ['void*', 'float*', 'float*']],
  'FMOD_Channel_Set3DConeSettings': ['int', ['void*', 'float', 'float', 'float']],
  'FMOD_Channel_Get3DConeSettings': ['int', ['void*', 'float*', 'float*', 'float*']],
  'FMOD_Channel_Set3DConeOrientation': ['int', ['void*', 'void*']],
  'FMOD_Channel_Get3DConeOrientation': ['int', ['void*', 'void*']],
  'FMOD_Channel_Set3DCustomRolloff': ['int', ['void*', 'void*', 'int']],
  'FMOD_Channel_Get3DCustomRolloff': ['int', ['void*', 'void**', 'int*']],
  'FMOD_Channel_Set3DOcclusion': ['int', ['void*', 'float', 'float']],
  'FMOD_Channel_Get3DOcclusion': ['int', ['void*', 'float*', 'float*']],
  'FMOD_Channel_Set3DSpread': ['int', ['void*', 'float']],
  'FMOD_Channel_Get3DSpread': ['int', ['void*', 'float*']],
  'FMOD_Channel_Set3DLevel': ['int', ['void*', 'float']],
  'FMOD_Channel_Get3DLevel': ['int', ['void*', 'float*']],
  'FMOD_Channel_Set3DDopplerLevel': ['int', ['void*', 'float']],
  'FMOD_Channel_Get3DDopplerLevel': ['int', ['void*', 'float*']],
  'FMOD_Channel_Set3DDistanceFilter': ['int', ['void*', 'int', 'float', 'float']],
  'FMOD_Channel_Get3DDistanceFilter': ['int', ['void*', 'int*', 'float*', 'float*']],
  'FMOD_Channel_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_Channel_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_Channel_SetFrequency': ['int', ['void*', 'float']],
  'FMOD_Channel_GetFrequency': ['int', ['void*', 'float*']],
  'FMOD_Channel_SetPriority': ['int', ['void*', 'int']],
  'FMOD_Channel_GetPriority': ['int', ['void*', 'int*']],
  'FMOD_Channel_SetPosition': ['int', ['void*', 'Uint', 'Uint']],
  'FMOD_Channel_GetPosition': ['int', ['void*', 'Uint*', 'Uint']],
  'FMOD_Channel_SetChannelGroup': ['int', ['void*', 'void*']],
  'FMOD_Channel_GetChannelGroup': ['int', ['void*', 'void**']],
  'FMOD_Channel_SetLoopCount': ['int', ['void*', 'int']],
  'FMOD_Channel_GetLoopCount': ['int', ['void*', 'int*']],
  'FMOD_Channel_SetLoopPoints': ['int', ['void*', 'Uint', 'Uint', 'Uint', 'Uint']],
  'FMOD_Channel_GetLoopPoints': ['int', ['void*', 'Uint*', 'Uint', 'Uint*', 'Uint']],
  'FMOD_Channel_IsVirtual': ['int', ['void*', 'int*']],
  'FMOD_Channel_GetCurrentSound': ['int', ['void*', 'void**']],
  'FMOD_Channel_GetIndex': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_GetSystemObject': ['int', ['void*', 'void**']],
  'FMOD_ChannelGroup_Stop': ['int', ['void*']],
  'FMOD_ChannelGroup_SetPaused': ['int', ['void*', 'int']],
  'FMOD_ChannelGroup_GetPaused': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_SetVolume': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_GetVolume': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_SetVolumeRamp': ['int', ['void*', 'int']],
  'FMOD_ChannelGroup_GetVolumeRamp': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_GetAudibility': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_SetPitch': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_GetPitch': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_SetMute': ['int', ['void*', 'int']],
  'FMOD_ChannelGroup_GetMute': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_SetReverbProperties': ['int', ['void*', 'int', 'float']],
  'FMOD_ChannelGroup_GetReverbProperties': ['int', ['void*', 'int', 'float*']],
  'FMOD_ChannelGroup_SetLowPassGain': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_GetLowPassGain': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_SetMode': ['int', ['void*', 'Uint']],
  'FMOD_ChannelGroup_GetMode': ['int', ['void*', 'Uint*']],
  'FMOD_ChannelGroup_SetCallback': ['int', ['void*', 'void*']],
  'FMOD_ChannelGroup_IsPlaying': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_SetPan': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_SetMixLevelsOutput': ['int', ['void*', 'float', 'float', 'float', 'float', 'float', 'float', 'float', 'float']],
  'FMOD_ChannelGroup_SetMixLevelsInput': ['int', ['void*', 'float*', 'int']],
  'FMOD_ChannelGroup_SetMixMatrix': ['int', ['void*', 'float*', 'int', 'int', 'int']],
  'FMOD_ChannelGroup_GetMixMatrix': ['int', ['void*', 'float*', 'int*', 'int*', 'int']],
  'FMOD_ChannelGroup_GetDSPClock': ['int', ['void*', 'Ulonglong*', 'Ulonglong*']],
  'FMOD_ChannelGroup_SetDelay': ['int', ['void*', 'Ulonglong', 'Ulonglong', 'int']],
  'FMOD_ChannelGroup_GetDelay': ['int', ['void*', 'Ulonglong*', 'Ulonglong*', 'int*']],
  'FMOD_ChannelGroup_AddFadePoint': ['int', ['void*', 'Ulonglong', 'float']],
  'FMOD_ChannelGroup_SetFadePointRamp': ['int', ['void*', 'Ulonglong', 'float']],
  'FMOD_ChannelGroup_RemoveFadePoints': ['int', ['void*', 'Ulonglong', 'Ulonglong']],
  'FMOD_ChannelGroup_GetFadePoints': ['int', ['void*', 'Uint*', 'Ulonglong*', 'float*']],
  'FMOD_ChannelGroup_GetDSP': ['int', ['void*', 'int', 'void**']],
  'FMOD_ChannelGroup_AddDSP': ['int', ['void*', 'int', 'void*']],
  'FMOD_ChannelGroup_RemoveDSP': ['int', ['void*', 'void*']],
  'FMOD_ChannelGroup_GetNumDSPs': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_SetDSPIndex': ['int', ['void*', 'void*', 'int']],
  'FMOD_ChannelGroup_GetDSPIndex': ['int', ['void*', 'void*', 'int*']],
  'FMOD_ChannelGroup_Set3DAttributes': ['int', ['void*', 'void*', 'void*']],
  'FMOD_ChannelGroup_Get3DAttributes': ['int', ['void*', 'void*', 'void*']],
  'FMOD_ChannelGroup_Set3DMinMaxDistance': ['int', ['void*', 'float', 'float']],
  'FMOD_ChannelGroup_Get3DMinMaxDistance': ['int', ['void*', 'float*', 'float*']],
  'FMOD_ChannelGroup_Set3DConeSettings': ['int', ['void*', 'float', 'float', 'float']],
  'FMOD_ChannelGroup_Get3DConeSettings': ['int', ['void*', 'float*', 'float*', 'float*']],
  'FMOD_ChannelGroup_Set3DConeOrientation': ['int', ['void*', 'void*']],
  'FMOD_ChannelGroup_Get3DConeOrientation': ['int', ['void*', 'void*']],
  'FMOD_ChannelGroup_Set3DCustomRolloff': ['int', ['void*', 'void*', 'int']],
  'FMOD_ChannelGroup_Get3DCustomRolloff': ['int', ['void*', 'void**', 'int*']],
  'FMOD_ChannelGroup_Set3DOcclusion': ['int', ['void*', 'float', 'float']],
  'FMOD_ChannelGroup_Get3DOcclusion': ['int', ['void*', 'float*', 'float*']],
  'FMOD_ChannelGroup_Set3DSpread': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_Get3DSpread': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_Set3DLevel': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_Get3DLevel': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_Set3DDopplerLevel': ['int', ['void*', 'float']],
  'FMOD_ChannelGroup_Get3DDopplerLevel': ['int', ['void*', 'float*']],
  'FMOD_ChannelGroup_Set3DDistanceFilter': ['int', ['void*', 'int', 'float', 'float']],
  'FMOD_ChannelGroup_Get3DDistanceFilter': ['int', ['void*', 'int*', 'float*', 'float*']],
  'FMOD_ChannelGroup_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_ChannelGroup_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_ChannelGroup_Release': ['int', ['void*']],
  'FMOD_ChannelGroup_AddGroup': ['int', ['void*', 'void*', 'int', 'void**']],
  'FMOD_ChannelGroup_GetNumGroups': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_GetGroup': ['int', ['void*', 'int', 'void**']],
  'FMOD_ChannelGroup_GetParentGroup': ['int', ['void*', 'void**']],
  'FMOD_ChannelGroup_GetName': ['int', ['void*', 'string', 'int']],
  'FMOD_ChannelGroup_GetNumChannels': ['int', ['void*', 'int*']],
  'FMOD_ChannelGroup_GetChannel': ['int', ['void*', 'int', 'void**']],
  'FMOD_SoundGroup_Release': ['int', ['void*']],
  'FMOD_SoundGroup_GetSystemObject': ['int', ['void*', 'void**']],
  'FMOD_SoundGroup_SetMaxAudible': ['int', ['void*', 'int']],
  'FMOD_SoundGroup_GetMaxAudible': ['int', ['void*', 'int*']],
  'FMOD_SoundGroup_SetMaxAudibleBehavior': ['int', ['void*', 'int']],
  'FMOD_SoundGroup_GetMaxAudibleBehavior': ['int', ['void*', 'int*']],
  'FMOD_SoundGroup_SetMuteFadeSpeed': ['int', ['void*', 'float']],
  'FMOD_SoundGroup_GetMuteFadeSpeed': ['int', ['void*', 'float*']],
  'FMOD_SoundGroup_SetVolume': ['int', ['void*', 'float']],
  'FMOD_SoundGroup_GetVolume': ['int', ['void*', 'float*']],
  'FMOD_SoundGroup_Stop': ['int', ['void*']],
  'FMOD_SoundGroup_GetName': ['int', ['void*', 'string', 'int']],
  'FMOD_SoundGroup_GetNumSounds': ['int', ['void*', 'int*']],
  'FMOD_SoundGroup_GetSound': ['int', ['void*', 'int', 'void**']],
  'FMOD_SoundGroup_GetNumPlaying': ['int', ['void*', 'int*']],
  'FMOD_SoundGroup_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_SoundGroup_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_DSP_Release': ['int', ['void*']],
  'FMOD_DSP_GetSystemObject': ['int', ['void*', 'void**']],
  'FMOD_DSP_AddInput': ['int', ['void*', 'void*', 'void**', 'int']],
  'FMOD_DSP_DisconnectFrom': ['int', ['void*', 'void*', 'void*']],
  'FMOD_DSP_DisconnectAll': ['int', ['void*', 'int', 'int']],
  'FMOD_DSP_GetNumInputs': ['int', ['void*', 'int*']],
  'FMOD_DSP_GetNumOutputs': ['int', ['void*', 'int*']],
  'FMOD_DSP_GetInput': ['int', ['void*', 'int', 'void**', 'void**']],
  'FMOD_DSP_GetOutput': ['int', ['void*', 'int', 'void**', 'void**']],
  'FMOD_DSP_SetActive': ['int', ['void*', 'int']],
  'FMOD_DSP_GetActive': ['int', ['void*', 'int*']],
  'FMOD_DSP_SetBypass': ['int', ['void*', 'int']],
  'FMOD_DSP_GetBypass': ['int', ['void*', 'int*']],
  'FMOD_DSP_SetWetDryMix': ['int', ['void*', 'float', 'float', 'float']],
  'FMOD_DSP_GetWetDryMix': ['int', ['void*', 'float*', 'float*', 'float*']],
  'FMOD_DSP_SetChannelFormat': ['int', ['void*', 'Uint', 'int', 'int']],
  'FMOD_DSP_GetChannelFormat': ['int', ['void*', 'Uint*', 'int*', 'int*']],
  'FMOD_DSP_GetOutputChannelFormat': ['int', ['void*', 'Uint', 'int', 'int', 'Uint*', 'int*', 'int*']],
  'FMOD_DSP_Reset': ['int', ['void*']],
  'FMOD_DSP_SetParameterFloat': ['int', ['void*', 'int', 'float']],
  'FMOD_DSP_SetParameterInt': ['int', ['void*', 'int', 'int']],
  'FMOD_DSP_SetParameterBool': ['int', ['void*', 'int', 'int']],
  'FMOD_DSP_SetParameterData': ['int', ['void*', 'int', 'void*', 'Uint']],
  'FMOD_DSP_GetParameterFloat': ['int', ['void*', 'int', 'float*', 'string', 'int']],
  'FMOD_DSP_GetParameterInt': ['int', ['void*', 'int', 'int*', 'string', 'int']],
  'FMOD_DSP_GetParameterBool': ['int', ['void*', 'int', 'int*', 'string', 'int']],
  'FMOD_DSP_GetParameterData': ['int', ['void*', 'int', 'void**', 'Uint*', 'string', 'int']],
  'FMOD_DSP_GetNumParameters': ['int', ['void*', 'int*']],
  'FMOD_DSP_GetParameterInfo': ['int', ['void*', 'int', 'void**']],
  'FMOD_DSP_GetDataParameterIndex': ['int', ['void*', 'int', 'int*']],
  'FMOD_DSP_ShowConfigDialog': ['int', ['void*', 'void*', 'int']],
  'FMOD_DSP_GetInfo': ['int', ['void*', 'string', 'Uint*', 'int*', 'int*', 'int*']],
  'FMOD_DSP_GetType': ['int', ['void*', 'int*']],
  'FMOD_DSP_GetIdle': ['int', ['void*', 'int*']],
  'FMOD_DSP_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_DSP_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_DSP_SetMeteringEnabled': ['int', ['void*', 'int', 'int']],
  'FMOD_DSP_GetMeteringEnabled': ['int', ['void*', 'int*', 'int*']],
  'FMOD_DSP_GetMeteringInfo': ['int', ['void*', 'void**', 'void**']],
  'FMOD_DSP_GetCPUUsage': ['int', ['void*', 'Uint*', 'Uint*']],
  'FMOD_DSPConnection_GetInput': ['int', ['void*', 'void**']],
  'FMOD_DSPConnection_GetOutput': ['int', ['void*', 'void**']],
  'FMOD_DSPConnection_SetMix': ['int', ['void*', 'float']],
  'FMOD_DSPConnection_GetMix': ['int', ['void*', 'float*']],
  'FMOD_DSPConnection_SetMixMatrix': ['int', ['void*', 'float*', 'int', 'int', 'int']],
  'FMOD_DSPConnection_GetMixMatrix': ['int', ['void*', 'float*', 'int*', 'int*', 'int']],
  'FMOD_DSPConnection_GetType': ['int', ['void*', 'int*']],
  'FMOD_DSPConnection_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_DSPConnection_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_Geometry_Release': ['int', ['void*']],
  'FMOD_Geometry_AddPolygon': ['int', ['void*', 'float', 'float', 'int', 'int', 'void*', 'int*']],
  'FMOD_Geometry_GetNumPolygons': ['int', ['void*', 'int*']],
  'FMOD_Geometry_GetMaxPolygons': ['int', ['void*', 'int*', 'int*']],
  'FMOD_Geometry_GetPolygonNumVertices': ['int', ['void*', 'int', 'int*']],
  'FMOD_Geometry_SetPolygonVertex': ['int', ['void*', 'int', 'int', 'void*']],
  'FMOD_Geometry_GetPolygonVertex': ['int', ['void*', 'int', 'int', 'void*']],
  'FMOD_Geometry_SetPolygonAttributes': ['int', ['void*', 'int', 'float', 'float', 'int']],
  'FMOD_Geometry_GetPolygonAttributes': ['int', ['void*', 'int', 'float*', 'float*', 'int*']],
  'FMOD_Geometry_SetActive': ['int', ['void*', 'int']],
  'FMOD_Geometry_GetActive': ['int', ['void*', 'int*']],
  'FMOD_Geometry_SetRotation': ['int', ['void*', 'void*', 'void*']],
  'FMOD_Geometry_GetRotation': ['int', ['void*', 'void*', 'void*']],
  'FMOD_Geometry_SetPosition': ['int', ['void*', 'void*']],
  'FMOD_Geometry_GetPosition': ['int', ['void*', 'void*']],
  'FMOD_Geometry_SetScale': ['int', ['void*', 'void*']],
  'FMOD_Geometry_GetScale': ['int', ['void*', 'void*']],
  'FMOD_Geometry_Save': ['int', ['void*', 'void*', 'int*']],
  'FMOD_Geometry_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_Geometry_GetUserData': ['int', ['void*', 'void**']],
  'FMOD_Reverb3D_Release': ['int', ['void*']],
  'FMOD_Reverb3D_Set3DAttributes': ['int', ['void*', 'void*', 'float', 'float']],
  'FMOD_Reverb3D_Get3DAttributes': ['int', ['void*', 'void*', 'float*', 'float*']],
  'FMOD_Reverb3D_SetProperties': ['int', ['void*', 'void*']],
  'FMOD_Reverb3D_GetProperties': ['int', ['void*', 'void*']],
  'FMOD_Reverb3D_SetActive': ['int', ['void*', 'int']],
  'FMOD_Reverb3D_GetActive': ['int', ['void*', 'int*']],
  'FMOD_Reverb3D_SetUserData': ['int', ['void*', 'void*']],
  'FMOD_Reverb3D_GetUserData': ['int', ['void*', 'void**']]
};
